#!/bin/bash

width="$1"
height="$2"

if [[ "$#" -eq 1 ]]; then
  height=$((("$width" << 15) / 100000))
elif [[ "$#" -lt 1 ]] || [[ "$#" -gt 2 ]]; then
  echo 'usage: mixmore <width> [<height>]' >&2
  exit 1
fi
python3 /tmp/pyth/pyth.py -n mixmin <<< "$width"$'\n'"$height"
